package br.com.mr.enums;

public enum Counters {
	REDUCER_WRITE,
	REDUCER_DISCART,
	LOGIN_MAPPER_WRITE,
	LOGIN_MAPPER_DISCART,
	RESPONSAVEL_MAPPER_WRITE,
	RESPONSAVEL_MAPPER_DISCART,
	REDUCER_COUNTER
}
